engines:
  eslint:
    enabled: true
    channel: "eslint-3"
    exclude_fingerprints:
    - cfee85432631e6611733e03940fcd231
    - 02e7e870efae3528cb8198cf20270c4e
  fixme:
    enabled: true
ecmaFeatures:
  modules: true
  jsx: true
env:
  es6: true
  node: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- __tests__/
