---

env:
  node: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 2017
  sourceType: module

extends:
  - 'airbnb-base/legacy'
  - plugin:import/errors
  - plugin:import/warnings
  
rules:
  no-console: 0
