---

<<<<<<< HEAD
  env:
    node: true
    jest: true
=======
env:
  node: true
>>>>>>> origin/master

parser: babel-eslint

parserOptions:
  ecmaVersion: 2017
  sourceType: module

extends:
  - 'airbnb-base'
  - plugin:import/errors
  - plugin:import/warnings
  
rules:
  no-console: 0
